### ISSUE TITLE
Build error after upgrading from 7.7.2 to 8.5.2

### ISSUE THREAD

**Issue by gmolk** [bugsnag/bugsnag-unity#906]
Hi, I hope you're doing well. We're using BugSnag in a Unity project targeting Linux. It was building fine on our previous version (7.7.2) but as soon as we upgraded to 8.5.2 (via UPM) our Linux builds immediately fail with the below error. I see that Linux is not on the Supported Platforms [doc page](https://docs.bugsnag.com/platforms/unity/platform-support/), so this isn't entirely unexpected, but we've been making Linux builds with no issues for quite some time now on previous versions. I also see a pretty old PR on this repository (https://github.com/bugsnag/bugsnag-unity/pull/831) for Linux support, so I imagine that's related. We'd like to stay on the latest stable version of this package, but we're currently blocked from upgrading due to this error.

### Steps to reproduce
1. Install BugSnag 8.5.2 via UPM.
2. Make a build targeting StandaloneLinux64.
3. See error:

```
Library/PackageCache/com.bugsnag.unitynotifier@dc55a3cdc6/Runtime/Bugsnag.cs(28,44): error CS0246: The type or namespace name 'NativeClient' could not be found (are you missing a using directive or an assembly reference?)
```

### Environment
* BugSnag version: 8.5.2
* Unity version: 2022.3.19f1
* macOS version (build machine): MacBook Pro 2023 Apple M2 Pro 32 GB running Sequoia 15.5
* Initializing bugsnag via a Unity GameObject or in code?: Initializing via code, but we're not experiencing a runtime issue, just a build issue
* Player Settings:
    * Scripting backend (Mono or IL2CPP): IL2CPP
    * API compatibility level for .NET: .NET Standard 2.1
    * Stack Trace level for all error types (None/ScriptOnly/Full): ScriptOnly for all

**Comment by clr182** [comment]
Hi @gmolk 

Thanks for reaching out. 

With the improvements to our native layer introduced in v8 of our unity notifier, we ended up dropping the Linux assembly reference as Linux is not officially supported at this time. 

While native Linux is not officially supported, we are discussing internally whether keeping minimum support which would allow builds to pass is something we would like to reintroduce at this moment. Once we've discussed this internally, we'll be sure to reach back out via this ticket thread with more information. Thanks for your patience!

**Comment by gmolk** [comment]
Hi @clr182 thanks for the quick response. I appreciate the context. I'll keep an eye on this thread for updates.

**Comment by mclack** [comment]
Hi @gmolk 

Thanks for your patience.

We've discussed this internally and have created a task to fix this build error. While I do not currently have an ETA we can share on when this fix will be available, we'll make sure to let you know here as soon as we have any further updates.
